plugin: aws_ec2
regions:
  - us-east-1

hostnames:
  - public-dns-name

filters:
  tag:flask_app: present
  instance-state-name: running

strict: False

vars:
  ansible_user: ec2-user
  ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/one.pem
