plugin: aws_ec2
regions:
  - us-east-1

filters:
  tag:flask_app: present
  instance-state-name: running

hostnames:
  - public-ip-address

keyed_groups:
  - key: tags.Name
    prefix: tag

vars:
  ansible_user: ec2-user
  ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/one.pem
