plugin: aws_ec2
regions:
  - us-east-1

keyed_groups:
  - key: tags.Role
    prefix: tag

filters:
  tag:Role: flask_app

hostnames:
  - ip-address

compose:
  ansible_host: public_ip_address

# Add this block if SSH connection issues persist
defaults:
  ansible_user: ec2-user
  ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/your-key.pem
  host_key_checking: false
